version: "3"
services:
  volt-dynamo:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: volt
      POSTGRES_PASSWORD: volt
      POSTGRES_DB: dynamo
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
