/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.capure.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroCompileError extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5378754289872725735L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroCompileError\",\"namespace\":\"io.github.capure.schema\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"fatal\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroCompileError> ENCODER =
      new BinaryMessageEncoder<AvroCompileError>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroCompileError> DECODER =
      new BinaryMessageDecoder<AvroCompileError>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroCompileError> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroCompileError> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroCompileError>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroCompileError to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroCompileError from a ByteBuffer. */
  public static AvroCompileError fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence message;
  @Deprecated public boolean fatal;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroCompileError() {}

  /**
   * All-args constructor.
   * @param message The new value for message
   * @param fatal The new value for fatal
   */
  public AvroCompileError(java.lang.CharSequence message, java.lang.Boolean fatal) {
    this.message = message;
    this.fatal = fatal;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message;
    case 1: return fatal;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message = (java.lang.CharSequence)value$; break;
    case 1: fatal = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'fatal' field.
   * @return The value of the 'fatal' field.
   */
  public java.lang.Boolean getFatal() {
    return fatal;
  }

  /**
   * Sets the value of the 'fatal' field.
   * @param value the value to set.
   */
  public void setFatal(java.lang.Boolean value) {
    this.fatal = value;
  }

  /**
   * Creates a new AvroCompileError RecordBuilder.
   * @return A new AvroCompileError RecordBuilder
   */
  public static io.github.capure.schema.AvroCompileError.Builder newBuilder() {
    return new io.github.capure.schema.AvroCompileError.Builder();
  }

  /**
   * Creates a new AvroCompileError RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroCompileError RecordBuilder
   */
  public static io.github.capure.schema.AvroCompileError.Builder newBuilder(io.github.capure.schema.AvroCompileError.Builder other) {
    return new io.github.capure.schema.AvroCompileError.Builder(other);
  }

  /**
   * Creates a new AvroCompileError RecordBuilder by copying an existing AvroCompileError instance.
   * @param other The existing instance to copy.
   * @return A new AvroCompileError RecordBuilder
   */
  public static io.github.capure.schema.AvroCompileError.Builder newBuilder(io.github.capure.schema.AvroCompileError other) {
    return new io.github.capure.schema.AvroCompileError.Builder(other);
  }

  /**
   * RecordBuilder for AvroCompileError instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroCompileError>
    implements org.apache.avro.data.RecordBuilder<AvroCompileError> {

    private java.lang.CharSequence message;
    private boolean fatal;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.github.capure.schema.AvroCompileError.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fatal)) {
        this.fatal = data().deepCopy(fields()[1].schema(), other.fatal);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroCompileError instance
     * @param other The existing instance to copy.
     */
    private Builder(io.github.capure.schema.AvroCompileError other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fatal)) {
        this.fatal = data().deepCopy(fields()[1].schema(), other.fatal);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }

    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public io.github.capure.schema.AvroCompileError.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public io.github.capure.schema.AvroCompileError.Builder clearMessage() {
      message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fatal' field.
      * @return The value.
      */
    public java.lang.Boolean getFatal() {
      return fatal;
    }

    /**
      * Sets the value of the 'fatal' field.
      * @param value The value of 'fatal'.
      * @return This builder.
      */
    public io.github.capure.schema.AvroCompileError.Builder setFatal(boolean value) {
      validate(fields()[1], value);
      this.fatal = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fatal' field has been set.
      * @return True if the 'fatal' field has been set, false otherwise.
      */
    public boolean hasFatal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fatal' field.
      * @return This builder.
      */
    public io.github.capure.schema.AvroCompileError.Builder clearFatal() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroCompileError build() {
      try {
        AvroCompileError record = new AvroCompileError();
        record.message = fieldSetFlags()[0] ? this.message : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.fatal = fieldSetFlags()[1] ? this.fatal : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroCompileError>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroCompileError>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroCompileError>
    READER$ = (org.apache.avro.io.DatumReader<AvroCompileError>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
