/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.capure.schema;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AvroJudgerResultCode {
  RESULT_SUCCESS, RESULT_WRONG_ANSWER, RESULT_CPU_TIME_LIMIT_EXCEEDED, RESULT_REAL_TIME_LIMIT_EXCEEDED, RESULT_MEMORY_LIMIT_EXCEEDED, RESULT_RUNTIME_ERROR, RESULT_SYSTEM_ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroJudgerResultCode\",\"namespace\":\"io.github.capure.schema\",\"symbols\":[\"RESULT_SUCCESS\",\"RESULT_WRONG_ANSWER\",\"RESULT_CPU_TIME_LIMIT_EXCEEDED\",\"RESULT_REAL_TIME_LIMIT_EXCEEDED\",\"RESULT_MEMORY_LIMIT_EXCEEDED\",\"RESULT_RUNTIME_ERROR\",\"RESULT_SYSTEM_ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
