/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.capure.schema;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AvroJudgerResultError {
  ERROR_NONE, ERROR_INVALID_CONFIG, ERROR_FORK_FAILED, ERROR_PTHREAD_FAILED, ERROR_WAIT_FAILED, ERROR_ROOT_REQUIRED, ERROR_LOAD_SECCOMP_FAILED, ERROR_SETRLIMIT_FAILED, ERROR_DUP2_FAILED, ERROR_SETUID_FAILED, ERROR_EXECVE_FAILED, ERROR_SPJ_ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroJudgerResultError\",\"namespace\":\"io.github.capure.schema\",\"symbols\":[\"ERROR_NONE\",\"ERROR_INVALID_CONFIG\",\"ERROR_FORK_FAILED\",\"ERROR_PTHREAD_FAILED\",\"ERROR_WAIT_FAILED\",\"ERROR_ROOT_REQUIRED\",\"ERROR_LOAD_SECCOMP_FAILED\",\"ERROR_SETRLIMIT_FAILED\",\"ERROR_DUP2_FAILED\",\"ERROR_SETUID_FAILED\",\"ERROR_EXECVE_FAILED\",\"ERROR_SPJ_ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
