/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.capure.schema;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TestCaseEventType {
  ADD, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TestCaseEventType\",\"namespace\":\"io.github.capure.schema\",\"symbols\":[\"ADD\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
